### ISSUE TITLE
Failed to activate the rails-i18n-autocomplete package

### ISSUE THREAD

**Issue by ldonnet** [ananevam/rails-i18n-autocomplete#1]
[Enter steps to reproduce below:]
1. Install Atom
2. Install packages : color-picker, pigments.... + rails-i18n-autocomplete

**Atom Version**: 1.4.1
**System**: Debian GNU/Linux
**Thrown From**: [rails-i18n-autocomplete](https://github.com/ananevam/rails-i18n-autocomplete) package, v0.2.0
### Stack Trace

Failed to activate the rails-i18n-autocomplete package

```
At duplicated mapping key at line 135, column 1:

    ^

YAMLException: duplicated mapping key at line 135, column 1:

    ^
  at generateError (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:161:10)
  at throwError (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:167:9)
  at storeMappingPair (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:304:7)
  at readBlockMapping (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1064:9)
  at composeNode (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
  at readBlockMapping (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
  at composeNode (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
  at readBlockMapping (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
  at composeNode (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
  at readDocument (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1490:3)
  at loadDocuments (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1546:5)
  at load (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1563:19)
  at Object.safeLoad (/home/luc/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1581:10)
  at Object.module.exports.RailsI18nAutocomplete.loadLocales (/home/luc/.atom/packages/rails-i18n-autocomplete/lib/rails-i18n-autocomplete.coffee:27:18)
  at Object.module.exports.RailsI18nAutocomplete.activate (/home/luc/.atom/packages/rails-i18n-autocomplete/lib/rails-i18n-autocomplete.coffee:40:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
  at /usr/share/atom/resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
  at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:483:46)
  at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
  at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.20.0
autocomplete-go, v0.1.1
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
linter-rails-best-practices, v0.2.2
pigments, v0.22.0
rails-i18n-autocomplete, v0.2.0

# Dev
No dev packages
```

**Comment by ananevam** [comment]
@ldonnet, fixed. now it works?

**Comment by ldonnet** [comment]
@ananevam Yes that fix the problem, awesome thanks!

**Comment by unmultimedio** [comment]
Hi there, I have exactly same issue but with a different trigger, a escape sequence `\'`
```
unknown escape sequence at line 405, column 64:
     ... out of dates, so new scores can\'t be created/updated"
                                         ^
Hide Stack Trace
YAMLException: unknown escape sequence at line 405, column 64:
     ... out of dates, so new scores can\'t be created/updated"
                                         ^
    at generateError (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDoubleQuotedScalar (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:615:9)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1332:13)
    at readBlockMapping (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/julian/.atom/packages/rails-i18n-autocomplete/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.RailsI18nAutocomplete.loadLocales (/Users/julian/.atom/packages/rails-i18n-autocomplete/lib/rails-i18n-autocomplete.coffee:27:18)
    at Object.module.exports.RailsI18nAutocomplete.activate (/Users/julian/.atom/packages/rails-i18n-autocomplete/lib/rails-i18n-autocomplete.coffee:42:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```
<img width="459" alt="screen shot 2016-06-20 at 11 03 24" src="https://cloud.githubusercontent.com/assets/4431392/16201443/09d25146-36d7-11e6-9502-d43be2d6a292.png">
